Jan3DevTest/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Jan3DevTest.Models;

namespace Jan3DevTest.Controllers
{
    public class CreateController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Create/
        public ActionResult Index()
        {
            return View(db.ttagrDataModels.ToList());
        }

        // GET: /Create/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ttagrDataModel ttagrdatamodel = db.ttagrDataModels.Find(id);
            if (ttagrdatamodel == null)
            {
                return HttpNotFound();
            }
            return View(ttagrdatamodel);
        }

        // GET: /Create/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Create/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Font,Color,Size,Timestamp,Text,Latitude,Longitude,Location")] ttagrDataModel ttagrdatamodel)
        {

            ttagrdatamodel.Timestamp = DateTime.Now;
            ttagrdatamodel.Size = 10;
            ttagrdatamodel.Font = "Courier";
            ttagrdatamodel.Color = "Black";

            if (ModelState.IsValid)
            {
                db.ttagrDataModels.Add(ttagrdatamodel);
                db.SaveChanges();
                return RedirectToAction("Index","View");
            }

            return View(ttagrdatamodel);
        }

        // GET: /Create/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ttagrDataModel ttagrdatamodel = db.ttagrDataModels.Find(id);
            if (ttagrdatamodel == null)
            {
                return HttpNotFound();
            }
            return View(ttagrdatamodel);
        }

        // POST: /Create/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Font,Color,Size,Timestamp,Text,Latitude,Longitude,Location")] ttagrDataModel ttagrdatamodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ttagrdatamodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ttagrdatamodel);
        }

        // GET: /Create/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ttagrDataModel ttagrdatamodel = db.ttagrDataModels.Find(id);
            if (ttagrdatamodel == null)
            {
                return HttpNotFound();
            }
            return View(ttagrdatamodel);
        }

        // POST: /Create/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ttagrDataModel ttagrdatamodel = db.ttagrDataModels.Find(id);
            db.ttagrDataModels.Remove(ttagrdatamodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Jan3DevTest/Controllers/ViewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Jan3DevTest.Models;
using System.Data.Entity.Core.Objects.DataClasses;

namespace Jan3DevTest.Controllers
{
    public class ViewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /View/
        public ActionResult Index()
        {
            return View(db.ttagrDataModels.ToList());
        }

        [HttpPost]
        public JsonResult ViewDataPost(double lat, double lon)
        {

            List<ttagrDataModel> tempList = new List<ttagrDataModel>();

            var tags = from t in db.ttagrDataModels
                       where Math.Abs(t.Latitude - lat) < 0.1 && Math.Abs(t.Longitude - lon) < 0.1
                       select t;

            tempList.AddRange(tags.ToList());
               
            ttagrDataModel tempModel = new ttagrDataModel("99999",lat,lon);
            tempList.Add(tempModel);
            tempList.Sort();
            tempList.Remove(tempModel);
            tempList = tempList.OrderByDescending(a => a.Timestamp).ToList();
            
            return Json(tempList.Take(10));
        }

        public ActionResult ViewData()
        {
            return View();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
   
        public ActionResult ViewGrafitti()
        {
            return View();
        }
    
    }
}

Jan3DevTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TTagr</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TTagr", "Index", "View", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Add Tag", "Create", "Create")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
           
                </ul>
        
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br /><br />
        @RenderBody()
        <hr />
        <footer>
            <p>Daydalus Studio - <a href="http://daydalus.net">daydalus.net</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("styles", required: false)
</body>
</html>